"""empty message

Revision ID: e5de4a05366d
Revises: 3092e9a8fb98
Create Date: 2019-02-10 12:22:40.173625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5de4a05366d'
down_revision = '3092e9a8fb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users',
                    'email',
                    existing_type=sa.VARCHAR(length=90),
                    nullable=True)
    op.alter_column('users',
                    'password',
                    existing_type=sa.VARCHAR(length=90),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users',
                    'password',
                    existing_type=sa.VARCHAR(length=90),
                    nullable=False)
    op.alter_column('users',
                    'email',
                    existing_type=sa.VARCHAR(length=90),
                    nullable=False)
    # ### end Alembic commands ###
